# Generated by Django 5.0.6 on 2024-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('shift', models.SmallIntegerField()),
                ('lot_number', models.BigIntegerField()),
                ('batch_number', models.BigIntegerField()),
                ('pp1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp4', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp5', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp6', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pp7', models.DecimalField(decimal_places=4, max_digits=10)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessParameterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('output', models.BooleanField()),
                ('value_02', models.IntegerField()),
                ('start', models.BooleanField()),
                ('stop', models.BooleanField()),
                ('value_01', models.IntegerField()),
            ],
        ),
    ]
